### ISSUE TITLE
KGemm module not found

### ISSUE THREAD

**Issue by rieram** [facebookresearch/FAMBench#76]
Hi guys,

I tried to run the "run_all.sh", but I get the following error:

import pytorch_gemm as kgemm
ModuleNotFoundError: No module named 'pytorch_gemm'

It seems that I dont have the kgemm module, but I can't find it anywhere, can you point me to a location where I can download a whl for it?

Thanks!

**Comment by xuzhao9** [comment]
You need to install FBGemm module from this repo: https://github.com/pytorch/FBGEMM. 
The command is:

```
pushd fbgemm_gpu
python setup.py install
```

**Comment by samiwilf** [comment]
Hi @rieram.  The issue you're seeing is caused by not pulling the param submodule.  You can fix this by running  git submodule update --init --recursive in the FAMBench repo. Thereafter at the root of the FAMBench repo, run "ls param". You should see that the folder isn't empty. In particular, you should see FAMBench/param/train/compute/pt/pytorch_gemm.py.   If that file is there, then "import pytorch_gemm as kgemm" will work.

**Comment by rieram** [comment]
Thank you. the git submodule update --init --recursive worked like a charm.
